# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "validate-total-price"
client_id = "6b343e767684e5f473df8806412e4439"
application_url = "https://encountered-information-advice-receive.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://encountered-information-advice-receive.trycloudflare.com/auth/callback",
  "https://encountered-information-advice-receive.trycloudflare.com/auth/shopify/callback",
  "https://encountered-information-advice-receive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "signature-dev-env.myshopify.com"
